export const threads = [
  {
    avatarImage: 'rainbow',
    name: 'Blackmore',
    username: '@CatchTheRainbow',
    relativeTime: '4h',
    datePosted: '12:45 • 20 Feb 2025',
    threadImage: '',
    thread: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eaque quos facere, rem ut cupiditate fugiat nihil velit! Quam nesciunt, quae facilis voluptatum sed culpa itaque ut totam reiciendis laboriosam natus!', //Thread
    liked: 'liked' as 'liked' | 'unlike',
    likeCount: '30',
    likedCount: '31',
    replyCount: '100',
  },
  {
    avatarImage: 'golden requim',
    name: 'Giorno',
    username: '@GoldenRequim',
    relativeTime: '1d',
    datePosted: '12:45 • 20 Feb 2025',
    threadImage: 'header-resized.png',
    thread: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quisquam hic expedita deleniti ipsam exercitationem iure enim molestiae repudiandae odio maxime?', //Thread
    liked: 'unlike' as 'unlike' | 'liked',
    likeCount: '56',
    likedCount: '57',
    replyCount: '100',
  },
  {
    avatarImage: 'diver down',
    name: 'Anasui',
    username: '@DiverDown',
    relativeTime: '12d',
    datePosted: '12:45 • 20 Feb 2025',
    threadImage: 'dio.jpg',
    thread: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eaque quos facere, rem ut cupiditate fugiat nihil velit! Quam nesciunt, quae facilis voluptatum sed culpa itaque ut totam reiciendis laboriosam natus!', //Thread
    liked: 'liked' as 'liked' | 'unlike',
    likeCount: '122',
    likedCount: '123',
    replyCount: '100',
  },
  {
    avatarImage: 'diver down',
    name: 'Anasui',
    username: '@DiverDown',
    relativeTime: '12d',
    datePosted: '12:45 • 20 Feb 2025',
    threadImage: '',
    thread: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eaque quos facere, rem ut cupiditate fugiat nihil velit! Quam nesciunt, quae facilis voluptatum sed culpa itaque ut totam reiciendis laboriosam natus!', //Thread
    liked: 'liked' as 'liked' | 'unlike',
    likeCount: '332',
    likedCount: '333',
    replyCount: '100',
  },
  {
    avatarImage: 'black sabbath',
    name: 'Polpo',
    username: '@BlackSabbath',
    relativeTime: '12m',
    datePosted: '12:45 • 20 Feb 2025',
    threadImage: 'abbachio.jpeg',
    thread: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eaque quos facere, rem ut cupiditate fugiat nihil velit! Quam nesciunt, quae facilis voluptatum sed culpa itaque ut totam reiciendis laboriosam natus!', //Thread
    liked: 'liked' as 'liked' | 'unlike',
    likeCount: '909',
    likedCount: '910',
    replyCount: '100',
  },
];
