export const users = [
  {
    image: 'sticky finger.png',
    fallback: 'B',
    name: 'Bucciaratti',
    username: 'StickyFinger',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'followed' as 'followed' | 'follow',
  },
  {
    image: 'golden requim.png',
    fallback: 'GG',
    name: 'Giorno',
    username: 'GoldenRequim',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'follow' as 'follow' | 'followed',
  },
  {
    image: 'diver down.png',
    fallback: 'A',
    name: 'Anasui',
    username: 'DiverDown',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'follow' as 'follow' | 'followed',
  },
  {
    image: 'black sabbath.png',
    fallback: 'P',
    name: 'Polpo',
    username: 'BlackSabbath',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'follow' as 'follow' | 'followed',
  },
  {
    image: 'rainbow.png',
    fallback: 'B',
    name: 'Blackmore',
    username: 'CatchTheRainbow',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'follow' as 'follow' | 'followed',
  },
];
