export const usersFollowed = [
  {
    page: 'bucciaratti',
    image: 'sticky finger',
    fallback: 'B',
    name: 'Bucciaratti',
    username: '@StickyFinger',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'followed' as 'followed' | 'follow',
  },
  {
    page: 'giorno',
    image: 'golden requim',
    fallback: 'GG',
    name: 'Giorno',
    username: '@GoldenRequim',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'followed' as 'followed' | 'follow',
  },
  {
    page: 'anasui',
    image: 'diver down',
    fallback: 'A',
    name: 'Anasui',
    username: '@DiverDown',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'followed' as 'followed' | 'follow',
  },
  {
    page: 'polpo',
    image: 'black sabbath',
    fallback: 'P',
    name: 'Polpo',
    username: '@BlackSabbath',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'followed' as 'followed' | 'follow',
  },
  {
    page: 'Blackmore',
    image: 'rainbow',
    fallback: 'B',
    name: 'Blackmore',
    username: '@CatchTheRainbow',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'followed' as 'followed' | 'follow',
  },
  {
    page: 'Vanilla Ice',
    image: 'cream',
    fallback: 'VI',
    name: 'Vanilla Ice',
    username: '@Cream',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'followed' as 'followed' | 'follow',
  },
  {
    page: 'Polnarref',
    image: 'silver chariot',
    fallback: 'JPP',
    name: 'Jean-Pierre Polnarref',
    username: '@SilverChariot',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'followed' as 'followed' | 'follow',
  },
  {
    page: 'Koichii',
    image: 'echo 3',
    fallback: 'K',
    name: 'Koichii',
    username: '@EchoAct3',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'followed' as 'followed' | 'follow',
  },
  {
    page: 'Diavollo',
    image: 'king crimson',
    fallback: 'D',
    name: 'Diavollo',
    username: '@KingCrimson',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'followed' as 'followed' | 'follow',
  },
];
