export const usersFollowed = [
  {
    page: 'bucciaratti',
    image: 'sticky finger.png',
    fallback: 'B',
    name: 'Bucciaratti',
    username: 'StickyFinger',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'followed' as 'followed' | 'follow',
  },
  {
    page: 'bucciaratti',
    image: 'sticky finger.png',
    fallback: 'B',
    name: 'Bucciaratti',
    username: 'StickyFinger',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'followed' as 'followed' | 'follow',
  },
  {
    page: 'giorno',
    image: 'golden requim.png',
    fallback: 'GG',
    name: 'Giorno',
    username: 'GoldenRequim',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'followed' as 'followed' | 'follow',
  },
  {
    page: 'anasui',
    image: 'diver down.png',
    fallback: 'A',
    name: 'Anasui',
    username: 'DiverDown',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'followed' as 'followed' | 'follow',
  },
  {
    page: 'polpo',
    image: 'black sabbath.png',
    fallback: 'P',
    name: 'Polpo',
    username: 'BlackSabbath',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'followed' as 'followed' | 'follow',
  },
  {
    page: 'Blackmore',
    image: 'rainbow.png',
    fallback: 'B',
    name: 'Blackmore',
    username: 'CatchTheRainbow',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'followed' as 'followed' | 'follow',
  },
  {
    page: 'Vanilla Ice',
    image: 'cream.png',
    fallback: 'VI',
    name: 'Vanilla Ice',
    username: 'Cream',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'followed' as 'followed' | 'follow',
  },
  {
    page: 'Polnarref',
    image: 'silver chariot.png',
    fallback: 'JPP',
    name: 'Jean-Pierre Polnarref',
    username: 'SilverChariot',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'followed' as 'followed' | 'follow',
  },
  {
    page: 'Koichii',
    image: 'echo 3.png',
    fallback: 'K',
    name: 'Koichii',
    username: 'EchoAct3',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'followed' as 'followed' | 'follow',
  },
  {
    page: 'Diavollo',
    image: 'king crimson.png',
    fallback: 'D',
    name: 'Diavollo',
    username: 'KingCrimson',
    bio: 'Syamalama lama lama dingdong',
    buttonType: 'followed' as 'followed' | 'follow',
  },
];
